'use strict';
// Negocios independientes; api() valida sesión y el servidor valida propiedad.
window.Business=(()=>{
 const modules=[['business','site','Negocio'],['products','cart','Productos'],['calculator','map','Calculadora de viajes'],['orders','cart','Pedidos'],['review','copy','Revisión de pagos'],['receipts','eye','Comprobantes'],['audit','site','Auditoría'],['completed','map','Viajes realizados'],['staff','user','Usuarios y permisos'],['commissions','copy','Comisiones y liquidaciones'],['customers','user','Clientes y bloqueos'],['payments','copy','Pagos'],['tickets','eye','Tickets'],['promotions','cart','Promociones'],['appearance','sun','Redes y apariencia'],['security','user','Seguridad de mi cuenta'],['bot','telegram','Bot de transferencias']];
 let selected=null,tab='business',rows=null;
 const input=(name,label,value='',type='text')=>field(name,label,value??'',type);
 function pick(name,label,options,value){return '<label>'+esc(label)+'<select name="'+name+'">'+options.map(([v,t])=>'<option value="'+esc(v)+'" '+(String(value)===v?'selected':'')+'>'+esc(t)+'</option>').join('')+'</select></label>'}
 function picture(name,label,value){return '<div class="image-control"><label>'+esc(label)+'<input class="image-file" type="file" data-upload="'+name+'" accept="image/jpeg,image/png,image/webp"></label><input type="hidden" name="'+name+'" value="'+esc(value||'')+'"><img data-image="'+name+'" alt="Vista previa de '+esc(label)+'" '+(value?'src="'+esc(value)+'"':'hidden')+'><button type="button" class="icon" data-clear="'+name+'" aria-label="Quitar '+esc(label)+'">'+Icon('close')+'</button><small>PNG, JPEG o WebP. Se optimiza antes de guardarse.</small></div>'}
 function fresh(){return data.sites.find(x=>x.id===selected.id)||selected}
 async function openBusiness(s,next='business'){selected=s;tab=next;rows=null;await draw()}
 async function draw(){selected=fresh();const s=selected,v=s.config;const permission={business:'settings',products:'products',orders:'orders',review:'payments',receipts:'reports',audit:'reports',completed:'reports',staff:'owner',commissions:'owner',customers:'owner',calculator:'orders',payments:'settings',tickets:'settings',appearance:'settings',promotions:'settings',bot:'owner'};const visible=modules.filter(([k])=>(k!=='bot'||s.bot_access===true)&&(!s.permissions||k==='security'||s.permissions.includes('owner')||s.permissions.includes(permission[k])));if(!visible.some(([k])=>k===tab))tab=visible[0]?.[0]||'security';
  open('Administración de '+(v.name||s.slug),'<div class="business-shell"><nav class="module-nav" aria-label="Módulos del negocio">'+visible.map(([key,icon,title])=>'<button class="module '+(tab===key?'selected':'')+'" data-module="'+key+'" type="button" aria-current="'+(tab===key?'page':'false')+'">'+Icon(icon)+'<span>'+title+'</span></button>').join('')+'</nav><section id="moduleBody"></section></div>');
  $('editor').classList.add('business-editor');$('editorBody').querySelectorAll('[data-module]').forEach(b=>b.onclick=run(async()=>{tab=b.dataset.module;await draw()}));
  const body=$('moduleBody');if(await BusinessStyle.render(s,tab,()=>draw()))return;if(await BusinessExtra.render(s,tab,()=>draw()))return;
  if(tab==='products'||tab==='orders'){rows=await api('site_orders',{site_id:s.id});if(tab==='products')products();else orders();return}
  let html='';
  if(tab==='business')html='<div class="grid">'+picture('logo','Logo del negocio',v.logo)+input('name','Nombre del negocio',v.name)+input('tagline','Descripción breve',v.tagline)+input('phone','Teléfono de llamadas',v.phone,'tel')+input('whatsapp','WhatsApp con código de país',v.whatsapp,'tel')+input('hours','Horarios de atención',v.hours)+input('address','Domicilio del negocio',v.address)+'</div><h4>Ubicación del negocio</h4><div id="businessMap"></div><button type="button" class="btn secondary" id="businessGps">'+Icon('pin')+'Mi ubicación</button><p id="gpsInfo" class="muted">Pulsa el mapa o arrastra el pin para ajustar la ubicación.</p><input type="hidden" name="lat" value="'+esc(v.lat??'')+'"><input type="hidden" name="lng" value="'+esc(v.lng??'')+'"><details><summary>Configuración del mapa</summary>'+pick('mapMode','Proveedor del mapa',[['shared','Usar el mapa de la plataforma'],['own','Utilizar mi propia configuración']],v.mapMode||'shared')+'<div id="ownMap">'+input('tiles','URL HTTPS de tiles (puede incluir {apiKey})',v.tiles)+input('mapKey','Clave pública para el mapa',v.mapKey)+'<p class="muted">Usa únicamente una clave pública de navegador, con restricciones del proveedor.</p></div></details>';
  if(tab==='payments')html=(s.bot_access?'<p>Publica cuentas manuales o vinculadas al lector de transferencias.</p><a class="btn secondary" href="'+esc(c.base+'gmail-conexion.html')+'" target="_blank" rel="noopener">'+Icon('copy')+'Vincular banca y correo</a>':'<p>Configura tus cuentas de transferencia. Los pagos se revisan manualmente.</p>')+'<div class="grid">'+[0,1,2].map(n=>{const b=(v.banks||[])[n]||{};return '<article class="card"><h4>Cuenta '+(n+1)+'</h4>'+input('bank_'+n,'Nombre exacto de la banca',b.bank)+(s.bot_access?pick('verification_'+n,'Validación del pago',[['manual','Revisión manual'],['linked','Bot de transferencias']],b.bank_slot?'linked':'manual')+input('slot_'+n,'Espacio vinculado (1 a 3)',b.bank_slot||n+1,'number'):'')+input('account_'+n,'Cuenta o CLABE',b.account)+input('beneficiary_'+n,'Beneficiario',b.beneficiary)+pick('type_'+n,'Tipo',[['clabe','CLABE'],['account','Cuenta']],b.account_type||'clabe')+'<input type="hidden" name="visible_'+n+'" value="'+(b.visible!==false)+'"><div class="row"><button type="button" class="icon" data-bank-visibility="'+n+'" aria-label="Mostrar u ocultar cuenta">'+Icon('eye')+'</button><span id="visibility'+n+'">'+(b.visible===false?'Oculta':'Visible')+'</span><button type="button" class="icon" data-bank-remove="'+n+'" aria-label="Eliminar cuenta del sitio">'+Icon('close')+'</button></div><p class="muted">La cuenta solo se muestra si está marcada como visible.</p></article>'}).join('')+'</div>';
  if(tab==='tickets')html='<div class="grid">'+input('ticketTitle','Título del ticket',v.ticketTitle||'Comprobante de pedido')+picture('headerImage','Imagen adicional del encabezado',v.headerImage)+input('ticketQr','Enlace HTTPS para el QR',v.ticketQr)+input('ticketFinal','Mensaje final',v.ticketFinal||'Guarda tu ticket para aclaraciones.')+'</div><p>El logo se toma del módulo Negocio. Los pedidos conservan folio, detalle de gastos, total y estado.</p><a class="btn secondary" href="store.html?site='+encodeURIComponent(s.slug)+'&preview=1&ticket=1" target="_blank" rel="noopener">'+Icon('eye')+'Vista previa del ticket</a>';
  if(tab==='appearance')html='<div class="grid">'+input('primaryColor','Color principal',v.primaryColor||'#c62828','color')+input('accentColor','Color de acento',v.accentColor||'#ffb300','color')+pick('theme','Tema inicial',[['light','Claro'],['dark','Oscuro']],v.theme||'light')+'</div><h4>Redes sociales</h4><div class="grid">'+['facebook','instagram','tiktok','x','website','whatsapp'].map(type=>input('social_'+type,type,(v.social||[]).find(x=>x.type===type)?.url||'','url')).join('')+'</div>';
  body.innerHTML='<h3 class="module-title">'+esc(modules.find(x=>x[0]===tab)[2])+'</h3><form id="businessForm">'+html+'<div class="module-save"><button class="btn">Guardar '+esc(modules.find(x=>x[0]===tab)[2])+'</button><a class="btn secondary" href="store.html?site='+encodeURIComponent(s.slug)+'&preview=1" target="_blank" rel="noopener">'+Icon('eye')+'Vista previa privada</a></div></form>';
  bindImages(s,'businessForm');if(tab==='business')businessMap(v);
  if(tab==='payments'){body.querySelectorAll('[data-bank-visibility]').forEach(b=>b.onclick=()=>{const n=b.dataset.bankVisibility,e=$('businessForm').elements['visible_'+n];e.value=e.value==='true'?'false':'true';$('visibility'+n).textContent=e.value==='true'?'Visible':'Oculta'});body.querySelectorAll('[data-bank-remove]').forEach(b=>b.onclick=()=>{$('businessForm').elements['account_'+b.dataset.bankRemove].value='';message('Cuenta retirada. Guarda el módulo para aplicar.')})}
  $('businessForm').onsubmit=run(async()=>{const form=$('businessForm');if(form.querySelector('[data-uploading]'))throw Error('Espera a que termine la imagen');const f=formObject('businessForm'),config={...s.config};
   if(tab==='business'){for(const k of ['logo','name','tagline','phone','whatsapp','hours','address','mapMode','tiles','mapKey'])config[k]=f[k];if(f.lat!==''){config.lat=Number(f.lat);config.lng=Number(f.lng)}}
   if(tab==='payments'){config.banks=[];for(let n=0;n<3;n++)if(f['account_'+n])config.banks.push({id:'bank-'+n,bank:f['bank_'+n],...(s.bot_access&&f['verification_'+n]==='linked'?{bank_slot:Number(f['slot_'+n])}:{}),account:f['account_'+n].replace(/\s/g,''),last4:f['account_'+n].replace(/\s/g,'').slice(-4),beneficiary:f['beneficiary_'+n],account_type:f['type_'+n],visible:f['visible_'+n]==='true'})}
   if(tab==='tickets')for(const k of ['ticketTitle','headerImage','ticketQr','ticketFinal'])config[k]=f[k];
   if(tab==='appearance'){for(const k of ['primaryColor','accentColor','theme'])config[k]=f[k];config.social=[];for(const type of ['facebook','instagram','tiktok','x','website','whatsapp'])if(f['social_'+type])config.social.push({type,url:f['social_'+type]})}
   await api('site_config',{site_id:s.id,config});await refresh();selected=fresh();message('Cambios guardados');await draw();
  });
 }
 function businessMap(v){let marker;bizMap=L.map('businessMap').setView([v.lat??19.11,v.lng??-104.34],15);L.tileLayer(Platform.tiles(v,data.map_defaults),{attribution:'© OpenStreetMap © CARTO'}).addTo(bizMap);
  function pin(lat,lng){const f=$('businessForm');f.elements.lat.value=lat;f.elements.lng.value=lng;if(marker)marker.setLatLng([lat,lng]);else{marker=L.marker([lat,lng],{draggable:true,icon:L.divIcon({html:Icon('pin'),className:'business-marker',iconSize:[30,36],iconAnchor:[15,36]})}).addTo(bizMap);marker.on('dragend',()=>{const p=marker.getLatLng();pin(p.lat,p.lng)})}bizMap.setView([lat,lng],16)}
  if(v.lat!=null)pin(v.lat,v.lng);bizMap.on('click',e=>pin(e.latlng.lat,e.latlng.lng));setTimeout(()=>bizMap?.invalidateSize(),100);
  $('businessGps').onclick=()=>{if(!navigator.geolocation)return message('GPS no disponible');navigator.geolocation.getCurrentPosition(p=>{pin(p.coords.latitude,p.coords.longitude);$('gpsInfo').textContent='Precisión estimada: '+Math.round(p.coords.accuracy)+' metros. Ajusta el pin si es necesario.'},e=>message(e.message),{enableHighAccuracy:true,maximumAge:0,timeout:20000})};
  const mode=$('businessForm').elements.mapMode;function advanced(){$('ownMap').hidden=mode.value!=='own'}mode.onchange=advanced;advanced();
 }
 function products(){const s=selected;$('moduleBody').innerHTML='<button class="btn" id="newBusinessProduct">'+Icon('cart')+'Añadir producto</button><div class="grid">'+rows.products.map(p=>'<article class="card product">'+(p.image?'<img src="'+esc(p.image)+'" alt="'+esc(p.name)+'">':'')+'<h3>'+esc(p.name)+'</h3><p>'+esc(p.category)+' · '+money(p.price)+' · '+p.stock+' disponibles</p><p>'+(p.active?'Visible':'Oculto')+'</p><div class="row"><button class="icon" data-edit-product="'+p.id+'" aria-label="Editar producto">'+Icon('gear')+'</button><button class="icon" data-hide-product="'+p.id+'" aria-label="Mostrar u ocultar producto">'+Icon('eye')+'</button></div></article>').join('')+'</div>';$('newBusinessProduct').onclick=()=>product(s,{});$('moduleBody').querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>product(s,rows.products.find(p=>p.id===b.dataset.editProduct)));$('moduleBody').querySelectorAll('[data-hide-product]').forEach(b=>b.onclick=run(async()=>{const p=rows.products.find(x=>x.id===b.dataset.hideProduct);await api('product',{...p,active:!p.active,site_id:s.id});await draw()}))}
 function orders(){const s=selected,canSettings=!s.permissions||s.permissions.includes('owner')||s.permissions.includes('settings'),canPayments=!s.permissions||s.permissions.includes('owner')||s.permissions.includes('payments');$('moduleBody').innerHTML=(canSettings?'<details class="card"><summary>Tarifas de entrega</summary><form id="deliveryFees">'+input('deliveryBase','Cargo base MXN',(s.config.deliveryBase??0)/100,'number')+input('perKm','Cargo por km lineal MXN',(s.config.perKm??0)/100,'number')+input('maxKm','Cobertura máxima km',s.config.maxKm??15,'number')+'<p class="muted">La tarifa usa distancia lineal desde el negocio.</p><button class="btn">Guardar tarifas</button></form></details>':'')+'<div id="deliveriesMap"></div><div class="row"><label>Filtrar<select id="orderFilter"><option value="all">Todos</option><option value="pending">Pago pendiente</option><option value="confirmed">Pago confirmado</option><option value="accepted">En recorrido</option><option value="delivered">Entregado</option></select></label></div><div id="businessOrders"></div>';
  if($('deliveryFees'))$('deliveryFees').onsubmit=run(async()=>{const f=formObject('deliveryFees');await api('site_config',{site_id:s.id,config:{...s.config,deliveryBase:Math.round(Number(f.deliveryBase)*100),perKm:Math.round(Number(f.perKm)*100),maxKm:Number(f.maxKm)}});await refresh();await draw();message('Tarifas guardadas')});
  bizMap=L.map('deliveriesMap').setView([s.config.lat??19.11,s.config.lng??-104.34],14);L.tileLayer(Platform.tiles(s.config,data.map_defaults),{attribution:'© OpenStreetMap © CARTO'}).addTo(bizMap);
  if(s.config.lat!=null)L.marker([s.config.lat,s.config.lng],{icon:L.divIcon({html:Icon('site'),className:'business-marker',iconSize:[30,30]})}).addTo(bizMap).bindPopup(esc(s.config.name));
  rows.orders.filter(o=>o.delivery.lat!=null&&!['delivered','cancelled'].includes(o.status)).forEach(o=>{const el=document.createElement('div');el.innerHTML='<strong>PED-'+o.folio+'</strong><p>'+esc(o.delivery.address)+'</p>';const btn=document.createElement('button');btn.className='btn';btn.textContent=o.payment_status==='confirmed'&&o.status==='new'?'Aceptar viaje':'Ver pedido';btn.onclick=run(async()=>{if(o.payment_status==='confirmed'&&o.status==='new'){await api('order_decision',{site_id:s.id,id:o.id,status:'accepted'});await draw()}else document.getElementById('order-'+o.id)?.scrollIntoView({behavior:'smooth'})});el.appendChild(btn);L.marker([o.delivery.lat,o.delivery.lng],{icon:L.divIcon({html:Icon('pin'),className:'business-marker',iconSize:[30,36]})}).addTo(bizMap).bindPopup(el)});setTimeout(()=>bizMap?.invalidateSize(),100);
  function list(){const filter=$('orderFilter').value;$('businessOrders').innerHTML=rows.orders.filter(o=>filter==='all'||o.payment_status===filter||o.status===filter).map(o=>'<article class="card" id="order-'+o.id+'"><h3>PED-'+o.folio+' · '+money(o.total)+'</h3><p>'+esc(o.customer.name)+' · '+esc(o.customer.phone)+'</p><p>'+esc(o.delivery.address||'Recoger en negocio')+'</p><p>Pago: '+labels[o.payment_status]+' · '+esc({new:'Nuevo',accepted:'En recorrido',delivered:'Entregado',cancelled:'Cancelado'}[o.status])+'</p><p>'+o.items.map(x=>esc(x.name)+' ('+x.qty+')').join(', ')+'</p><div class="row">'+(canPayments&&o.payment_status!=='confirmed'?'<button class="btn secondary" data-review="'+o.id+'">Revisar pago</button>':'')+(o.payment_status==='confirmed'&&o.status==='new'?'<button class="btn" data-stage="'+o.id+'" data-status="accepted">Aceptar</button>':'')+(o.status==='accepted'?'<button class="btn" data-stage="'+o.id+'" data-status="delivered">Finalizar entrega</button>':'')+(o.delivery.lat!=null?'<a class="btn secondary" href="https://www.google.com/maps/search/?api=1&query='+o.delivery.lat+','+o.delivery.lng+'" target="_blank" rel="noopener">'+Icon('map')+'Destino</a>':'')+'</div></article>').join('');$('businessOrders').querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>reviewOrder(b.dataset.review));$('businessOrders').querySelectorAll('[data-stage]').forEach(b=>b.onclick=run(async()=>{await api('order_decision',{site_id:s.id,id:b.dataset.stage,status:b.dataset.status});await draw()}))}list();$('orderFilter').onchange=list;
 }
 function reviewOrder(id){open('Revisar pago del pedido','<form id="businessReview">'+pick('status','Resultado',[['confirmed','Confirmado'],['denied','Denegado'],['false','Falso']],'confirmed')+input('reason','Motivo obligatorio')+'<button class="btn">Registrar decisión</button></form>');$('businessReview').onsubmit=run(async()=>{await api('order_payment_decision',{site_id:selected.id,id,...formObject('businessReview')});tab='orders';await draw()})}
 function product(s,p){open('Editar producto','<form id="businessProduct"><div class="grid">'+picture('image','Fotografía del producto',p.image)+input('name','Nombre',p.name)+input('description','Descripción',p.description)+input('category','Categoría',p.category||'Comida')+input('price','Precio MXN',(p.price??0)/100,'number')+input('stock','Existencias',p.stock??0,'number')+pick('active','Disponibilidad',[['true','Visible'],['false','Oculto']],String(p.active!==false))+pick('icon','Icono SVG',Object.keys(FoodIcons).map(k=>[k,k]),p.icon||'plate')+'</div><button class="btn">Guardar producto</button><button type="button" class="btn secondary" id="backProducts">Volver</button></form>');bindImages(s,'businessProduct');$('backProducts').onclick=run(()=>openBusiness(s,'products'));$('businessProduct').onsubmit=run(async()=>{if($('businessProduct').querySelector('[data-uploading]'))throw Error('Espera a que termine la imagen');const f=formObject('businessProduct');await api('product',{...f,id:p.id,site_id:s.id,price:Math.round(Number(f.price)*100),stock:Number(f.stock),active:f.active==='true'});await openBusiness(s,'products')})}
 async function optimize(file){if(file.size>15*1024*1024)throw Error('Selecciona una foto de hasta 15 MB');let bitmap;try{bitmap=await createImageBitmap(file)}catch{throw Error('No se pudo abrir la foto. Exporta como JPEG o PNG.')};if(bitmap.width*bitmap.height>48000000){bitmap.close();throw Error('Reduce las dimensiones de la foto')};const factor=Math.min(1,1800/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*factor);canvas.height=Math.round(bitmap.height*factor);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const mime=file.type==='image/png'?'image/png':'image/jpeg';return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('No se pudo preparar la imagen')),mime,.85))}
 function bindImages(s,formId){const form=$(formId);form.querySelectorAll('[data-upload]').forEach(el=>el.onchange=run(async()=>{const file=el.files[0];if(!file)return;el.dataset.uploading='true';try{message('Preparando imagen…');const blob=await optimize(file),fd=new FormData();fd.set('site_id',s.id);fd.set('file',blob,blob.type==='image/png'?'image.png':'image.jpg');const auth=await client.auth.getSession();if(!auth.data.session)throw Error('Inicia sesión');const result=await fetch(c.url+'/functions/v1/saas-platform',{method:'POST',headers:{apikey:c.key,Authorization:'Bearer '+auth.data.session.access_token},body:fd}),r=await result.json();if(!result.ok)throw Error(r.error);form.elements[el.dataset.upload].value=r.data.url;const img=form.querySelector('[data-image="'+el.dataset.upload+'"]');img.src=r.data.url;img.hidden=false;message('Imagen cargada. Guarda el módulo para aplicarla.')}finally{delete el.dataset.uploading}}));form.querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>{form.elements[b.dataset.clear].value='';form.querySelector('[data-image="'+b.dataset.clear+'"]').hidden=true})}
 function mapDefaults(){const v=data.map_defaults||{};open('Mapa predeterminado de la plataforma','<form id="mapDefaults">'+input('tiles','URL HTTPS de tiles que utilizarán los negocios',v.tiles)+input('mapKey','Clave pública del mapa (opcional)',v.mapKey)+'<p>La URL puede incluir {apiKey}. Utiliza la configuración de navegador de tu proveedor. Los negocios también pueden elegir su propia configuración.</p><button class="btn">Guardar mapa predeterminado</button></form>');$('mapDefaults').onsubmit=run(async()=>{await api('map_defaults',formObject('mapDefaults'));$('editor').close();await refresh();message('Mapa predeterminado guardado')})}
 return {open:openBusiness,product,mapDefaults,picture,bindImages};
})();
