'use strict';
window.BusinessExtra=(()=>{
 const names={new:'Nuevo',accepted:'En recorrido',delivered:'Entregado',cancelled:'Cancelado'};
 const permissions=[['products','Productos'],['orders','Pedidos y entregas'],['payments','Revisión de pagos'],['settings','Configuración del negocio'],['reports','Comprobantes y reportes']];
 const input=(n,l,v='',t='text')=>field(n,l,v,t);
 function button(id,text,icon='site'){return '<button type="button" class="btn secondary" id="'+id+'">'+Icon(icon)+esc(text)+'</button>'}
 async function records(s){return (await api('site_orders',{site_id:s.id})).orders}
 function summaries(orders){return '<div class="metric-grid">'+[['Pedidos',orders.length],['Por aprobar',orders.filter(o=>o.payment_status==='pending').length],['Pago confirmado',orders.filter(o=>o.payment_status==='confirmed').length],['Entregados',orders.filter(o=>o.status==='delivered').length]].map(([label,value])=>'<article class="metric"><small>'+label+'</small><strong>'+value+'</strong></article>').join('')+'</div>'}
 function card(o){return '<article class="card"><div class="row"><h4>PED-'+o.folio+'</h4><strong>'+money(o.total)+'</strong></div><p>'+esc(o.customer.name)+' · '+esc(o.customer.phone)+'</p><p>'+esc(o.delivery.address||'Recoger en el negocio')+'</p><p>'+esc(labels[o.payment_status])+' · '+esc(names[o.status])+'</p><small>'+esc(new Date(o.created_at).toLocaleString('es-MX'))+'</small></article>'}
 async function render(s,tab,redraw){const host=$('moduleBody');if(!['dashboard','calculator','review','receipts','audit','completed','staff','commissions','customers','security','bot'].includes(tab))return false;
  if(tab==='dashboard'){
    const rows=await records(s),pending=rows.filter(o=>o.payment_status==='pending'&&o.status!=='cancelled').length,confirmed=rows.filter(o=>o.payment_status==='confirmed').length,inRoute=rows.filter(o=>o.status==='accepted').length,delivered=rows.filter(o=>o.status==='delivered').length;
    const revenue=rows.filter(o=>o.payment_status==='confirmed').reduce((n,o)=>n+(o.total||0),0);
    host.innerHTML='<h3>Dashboard</h3><div class="admin-dashboard">'+[
      ['Pedidos',rows.length,'orders'],['Por revisar',pending,'copy'],['Confirmados',confirmed,'receipt'],['En recorrido',inRoute,'map'],['Entregados',delivered,'site']
    ].map(([label,value,icon])=>'<article class="admin-kpi">'+Icon(icon)+'<span>'+label+'</span><strong>'+value+'</strong></article>').join('')+'</div><div class="admin-grid two"><article class="section-card"><h3>Resumen operativo</h3><p class="large">'+money(revenue)+'</p><p class="muted">Total de pedidos con pago confirmado.</p><div class="toolbar"><button class="btn" data-go-module="orders">'+Icon('orders')+'<span>Ver pedidos</span></button><button class="btn secondary" data-go-module="review">'+Icon('copy')+'<span>Revisar pagos</span></button></div></article><article class="section-card"><h3>Accesos rápidos</h3><div class="toolbar"><button class="btn secondary" data-go-module="products">'+Icon('products')+'<span>Productos</span></button><button class="btn secondary" data-go-module="calculator">'+Icon('calculator')+'<span>Calcular ruta</span></button><button class="btn secondary" data-go-module="business">'+Icon('business')+'<span>Negocio</span></button><button class="btn secondary" data-go-module="appearance">'+Icon('palette')+'<span>Personalización</span></button></div></article></div>';
    host.querySelectorAll('[data-go-module]').forEach(b=>b.onclick=()=>Business.open(s,b.dataset.goModule));
    return true
  }
  if(tab==='security'){host.innerHTML='<h3>Seguridad de mi cuenta</h3><article class="card"><p>Sesión: '+esc((await client.auth.getSession()).data.session?.user?.email||'Cuenta autenticada')+'</p><form id="businessPassword">'+input('password','Nueva contraseña','','password')+input('confirmation','Confirmar contraseña','','password')+'<button class="btn">'+Icon('user')+'Cambiar contraseña</button></form><p>'+button('businessLogout','Cerrar sesión','user')+'</p></article>';$('businessPassword').onsubmit=run(async()=>{const f=formObject('businessPassword');if(f.password.length<12||f.password!==f.confirmation)throw Error('Usa al menos 12 caracteres y confirma la misma contraseña');const r=await client.auth.updateUser({password:f.password});if(r.error)throw r.error;$('businessPassword').reset();message('Contraseña actualizada')});$('businessLogout').onclick=run(async()=>{await client.auth.signOut();$('editor').close();location.reload()});return true}
  if(tab==='bot'){const r=await api('site_bot',{site_id:s.id});host.innerHTML='<h3>Bot de transferencias</h3><article class="card"><span class="pill">Suscripción activa</span><p>'+(r.expires_at?'Vence: '+esc(new Date(r.expires_at).toLocaleString('es-MX')):'Acceso del creador')+'</p><p>Configura y prueba hasta tres bancas y sus correos desde tu cuenta propietaria.</p><a class="btn" href="'+esc(c.base+'gmail-conexion.html')+'" target="_blank" rel="noopener">'+Icon('copy')+'Bancas, correos y movimientos</a></article><div class="grid">'+r.banks.map(b=>'<article class="card"><h4>Espacio '+b.slot+' · '+esc(b.bank)+'</h4><p>Terminación '+esc(b.last4)+'</p><p>'+(b.tested_at?'Conexión probada':'Pendiente de prueba')+'</p></article>').join('')+'</div><p>El bot se habilita por la suscripción del propietario; la vinculación no comparte credenciales con otros administradores.</p>';return true}
  if(tab==='calculator'){
    const v=s.config,origin={lat:Number(v.lat),lng:Number(v.lng),address:v.address||'Origen del negocio'};let tripMap=null,destination=null,routeLayer=null,lastRoute=null;
    host.innerHTML='<h3>Calculadora de viajes</h3><div class="admin-grid two"><article class="section-card"><h3>Ruta y distancia</h3><div class="field"><label>Origen</label><input class="input" value="'+esc(origin.address)+'" disabled></div><div class="field"><label>Destino</label><input class="input" id="tripDestination" placeholder="Calle, colonia y ciudad"></div><div class="toolbar"><button type="button" class="btn secondary" id="tripSearch">'+Icon('pin')+'<span>Buscar destino</span></button><button type="button" class="btn ghost" id="tripGps">'+Icon('map')+'<span>Mi ubicación</span></button></div><div id="tripSearchResults" class="stack"></div><div id="tripRouteMap" class="map route-admin-map"></div><p id="tripRouteInfo" class="muted">Busca una dirección, usa GPS o marca el destino en el mapa.</p></article><article class="section-card"><h3>Costos del viaje</h3><div class="admin-grid two">'+input('products','Productos / insumos MXN',0,'number')+input('fuelPrice','Combustible por litro MXN',v.fuelPrice||24.5,'number')+input('efficiency','Rendimiento km/l',v.efficiency||13,'number')+input('margin','Margen adicional %',v.tripMargin||0,'number')+'</div><label class="row"><input type="checkbox" id="roundTrip" '+(v.roundTrip?'checked':'')+'><span>Calcular ida y vuelta</span></label><div class="result-grid" style="margin-top:12px"><article class="metric"><span>Distancia</span><strong id="tripKm">0.00 km</strong></article><article class="metric"><span>Tiempo</span><strong id="tripMinutes">0 min</strong></article><article class="metric"><span>Combustible</span><strong id="tripFuel">$0.00</strong></article><article class="metric"><span>Total sugerido</span><strong id="tripCost">$0.00</strong></article></div><div class="toolbar" style="margin-top:12px"><button type="button" class="btn" id="useTripRate">'+Icon('save')+'<span>Usar esta tarifa</span></button></div><small>La ruta se calcula por vialidades con OSRM. El mapa utiliza la configuración CARTO del negocio.</small></article></div>';
    const mapEl=$('tripRouteMap'),info=$('tripRouteInfo'),kmEl=$('tripKm'),minEl=$('tripMinutes'),fuelEl=$('tripFuel'),costEl=$('tripCost'),products=$('tripCalcProducts');
    const moneyLocal=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n);
    function tileUrl(){return Platform.tiles(v,data.map_defaults)}
    function labeled(kind){return L.divIcon({className:'',html:'<div class="route-pin '+(kind==='destination'?'destination':'')+'"><div class="route-pin-label">'+(kind==='destination'?'Entrega':'Salida')+'</div><div class="route-pin-stem"></div>'+Icon('pin')+'</div>',iconSize:[110,78],iconAnchor:[55,78]})}
    function calcCost(){
      if(!lastRoute)return;
      const round=$('roundTrip').checked?2:1,km=lastRoute.km*round,extra=Number(document.querySelector('[name="products"]').value||0),fuelPrice=Number(document.querySelector('[name="fuelPrice"]').value||0),eff=Number(document.querySelector('[name="efficiency"]').value||1),margin=Number(document.querySelector('[name="margin"]').value||0);
      const fuel=(km/Math.max(.1,eff))*fuelPrice,base=((v.deliveryBase||0)/100)+((v.perKm||0)/100)*km,total=(base+fuel+extra)*(1+Math.max(0,margin)/100);
      kmEl.textContent=km.toFixed(2)+' km';minEl.textContent=Math.ceil(lastRoute.minutes*round)+' min';fuelEl.textContent=moneyLocal(fuel);costEl.textContent=moneyLocal(total);costEl.dataset.rate=String(total);costEl.dataset.km=String(km)
    }
    async function routeTo(lat,lng,label){
      destination={lat,lng,label};info.textContent='Calculando ruta por vialidades…';
      const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{
        const r=await fetch('https://router.project-osrm.org/route/v1/driving/'+origin.lng+','+origin.lat+';'+lng+','+lat+'?overview=full&geometries=geojson',{signal:c.signal});
        if(!r.ok)throw Error('No se pudo calcular la ruta');const d=await r.json();if(!d.routes?.length)throw Error('No se encontró una ruta transitable');
        lastRoute={km:d.routes[0].distance/1000,minutes:d.routes[0].duration/60,geo:d.routes[0].geometry};if(routeLayer)tripMap.removeLayer(routeLayer);routeLayer=L.geoJSON(lastRoute.geo,{style:{weight:5,opacity:.9}}).addTo(tripMap);
        [...tripMap._layers].forEach(()=>{});tripMap.eachLayer(layer=>{if(layer instanceof L.Marker&&layer.options?.title==='destination')tripMap.removeLayer(layer)});
        L.marker([lat,lng],{draggable:true,title:'destination',icon:labeled('destination')}).addTo(tripMap).on('dragend',e=>{const p=e.target.getLatLng();routeTo(p.lat,p.lng,'Punto designado')});
        tripMap.fitBounds(routeLayer.getBounds(),{padding:[35,35],maxZoom:16});info.textContent=label+' · '+lastRoute.km.toFixed(2)+' km · '+Math.ceil(lastRoute.minutes)+' min estimados';calcCost()
      }catch(e){info.textContent=e.message||'No fue posible calcular la ruta'}finally{clearTimeout(timer)}
    }
    if(!Number.isFinite(origin.lat)||!Number.isFinite(origin.lng)){mapEl.innerHTML='<div class="notice">Configura primero el origen del negocio en Negocio.</div>';return true}
    tripMap=L.map('tripRouteMap',{zoomAnimation:false,fadeAnimation:false}).setView([origin.lat,origin.lng],13);L.tileLayer(tileUrl(),{attribution:'© OpenStreetMap © CARTO'}).addTo(tripMap);L.marker([origin.lat,origin.lng],{icon:labeled('origin')}).addTo(tripMap);tripMap.on('click',e=>routeTo(e.latlng.lat,e.latlng.lng,'Punto marcado en el mapa'));setTimeout(()=>tripMap.invalidateSize(),100);
    $('tripSearch').onclick=run(async()=>{const q=$('tripDestination').value.trim();if(!q)throw Error('Escribe una dirección');const box=$('tripSearchResults');box.textContent='Buscando…';const c=new AbortController(),timer=setTimeout(()=>c.abort(),12000);try{const r=await fetch('https://photon.komoot.io/api/?limit=5&q='+encodeURIComponent(q),{signal:c.signal,headers:{'Accept-Language':'es'}});if(!r.ok)throw Error('El buscador no respondió');const d=await r.json(),features=d.features||[];box.innerHTML=features.length?features.map((p,i)=>'<button type="button" class="btn ghost full" data-trip-result="'+i+'">'+esc([p.properties?.name,p.properties?.street,p.properties?.city,p.properties?.state].filter(Boolean).join(', '))+'</button>').join(''):'<p class="muted">No se encontraron resultados. Marca el destino en el mapa.</p>';box.querySelectorAll('[data-trip-result]').forEach((b,i)=>b.onclick=()=>{const p=features[i],coords=p.geometry.coordinates,label=[p.properties?.name,p.properties?.street,p.properties?.city,p.properties?.state].filter(Boolean).join(', ');$('tripDestination').value=label;box.innerHTML='';routeTo(coords[1],coords[0],label)})}finally{clearTimeout(timer)}});
    $('tripGps').onclick=()=>{if(!navigator.geolocation)return message('GPS no disponible');navigator.geolocation.getCurrentPosition(p=>routeTo(p.coords.latitude,p.coords.longitude,'Tu ubicación actual'),e=>message(e.message),{enableHighAccuracy:true,timeout:15000,maximumAge:0})};
    ['products','fuelPrice','efficiency','margin'].forEach(n=>document.querySelector('[name="'+n+'"]').addEventListener('input',calcCost));$('roundTrip').onchange=calcCost;
    $('useTripRate').onclick=run(async()=>{if(!lastRoute)throw Error('Calcula primero una ruta');const km=Number(costEl.dataset.km||0),total=Number(costEl.dataset.rate||0);if(!Number.isFinite(km+total)||km<=0)throw Error('La ruta no es válida');const perKm=Math.round((total/km)*100);await api('site_config',{site_id:s.id,config:{...s.config,perKm,roundTrip:$('roundTrip').checked,fuelPrice:Number(document.querySelector('[name="fuelPrice"]').value||0),efficiency:Number(document.querySelector('[name="efficiency"]').value||1),tripMargin:Number(document.querySelector('[name="margin"]').value||0)}});await refresh();message('Tarifa por km actualizada con este cálculo')});
    return true
  }
  if(tab==='staff'){const users=await api('site_staff',{site_id:s.id});host.innerHTML='<h3>Usuarios y permisos</h3><article class="card"><p>La persona debe crear primero su cuenta en la plataforma. El acceso que asignes solo aplica a este negocio.</p><form id="staffForm">'+input('email','Correo de la cuenta','','email')+'<div class="permission-grid">'+permissions.map(([key,label])=>'<label class="check"><input type="checkbox" name="'+key+'">'+label+'</label>').join('')+'</div><button class="btn">Guardar acceso</button></form></article><div class="grid">'+users.map(u=>'<article class="card"><h4>'+esc(u.email)+'</h4><p>'+u.permissions.map(p=>esc(permissions.find(x=>x[0]===p)?.[1]||p)).join(', ')+'</p><button class="btn secondary" data-remove-staff="'+u.user_id+'">Retirar acceso</button></article>').join('')+'</div>';$('staffForm').onsubmit=run(async()=>{const f=formObject('staffForm');await api('staff_save',{site_id:s.id,email:f.email,permissions:permissions.filter(([p])=>f[p]).map(([p])=>p)});await redraw()});host.querySelectorAll('[data-remove-staff]').forEach(b=>b.onclick=run(async()=>{await api('staff_remove',{site_id:s.id,user_id:b.dataset.removeStaff});await redraw()}));return true}
  if(tab==='audit'){const r=await api('site_report',{site_id:s.id});host.innerHTML='<h3>Auditoría</h3><p>Acciones realizadas en este negocio. Se muestran hasta 200 registros recientes.</p><div class="audit-list">'+r.audit.map(a=>'<article class="card"><strong>'+esc(a.operation)+'</strong><p>'+esc(new Date(a.created_at).toLocaleString('es-MX'))+'</p><small>Usuario: '+esc(a.actor)+' · Registro: '+esc(a.target||'Negocio')+'</small></article>').join('')+'</div>';return true}
  const rows=await records(s);
  if(tab==='review'){host.innerHTML='<h3>Revisión de pagos</h3>'+summaries(rows)+'<div class="grid">'+rows.filter(o=>o.payment_status==='pending'&&o.status!=='cancelled').map(o=>'<div>'+card(o)+'<button class="btn" data-review-order="'+o.id+'">Revisar transferencia</button></div>').join('')+'</div><p>Verifica el movimiento real antes de aprobar. El bot confirma automáticamente únicamente las coincidencias verificadas.</p>';host.querySelectorAll('[data-review-order]').forEach(b=>b.onclick=()=>{open('Revisar pago PED-'+rows.find(o=>o.id===b.dataset.reviewOrder).folio,'<form id="paymentReview"><label>Resultado<select name="status"><option value="confirmed">Confirmado</option><option value="denied">Denegado</option><option value="false">Falso</option></select></label>'+input('reason','Motivo obligatorio')+'<button class="btn">Registrar</button></form>');$('paymentReview').onsubmit=run(async()=>{await api('order_payment_decision',{site_id:s.id,id:b.dataset.reviewOrder,...formObject('paymentReview')});await Business.open(s,'review')})});return true}
  if(tab==='completed'){host.innerHTML='<h3>Viajes realizados</h3>'+summaries(rows)+'<div class="grid">'+rows.filter(o=>o.status==='delivered').map(card).join('')+'</div><small>Historial de los últimos 200 pedidos. Las comisiones se registran al aceptar el viaje.</small>';return true}
  if(tab==='commissions'){const completed=rows.filter(o=>o.status==='delivered');host.innerHTML='<h3>Comisiones y liquidaciones</h3><article class="card"><form id="commissionForm">'+input('commissionPercent','Comisión del negocio sobre el traslado (%)',s.config.commissionPercent||0,'number')+'<p>El repartidor recibe el resto del traslado. Los productos e insumos pertenecen al negocio. La tarifa queda registrada al aceptar el viaje; cambiarla no altera viajes anteriores.</p><button class="btn">Guardar comisión</button></form></article><div class="metric-grid"><article class="metric"><small>Pendiente de liquidar al repartidor</small><strong>'+money(completed.filter(o=>!o.settled_at).reduce((v,o)=>v+(o.courier_earning||0),0))+'</strong></article></div><div class="grid">'+completed.map(o=>'<article class="card"><h4>PED-'+o.folio+'</h4><p>Traslado: '+money(o.shipping)+' · Repartidor: '+money(o.courier_earning||0)+'</p><p>Productos e insumos: '+money(o.subtotal)+' · Parte del negocio: '+money(o.total-(o.courier_earning||0))+'</p><small>Repartidor: '+esc(o.courier_id||'Viaje anterior sin asignación')+'</small><p>'+(o.settled_at?'Liquidado '+esc(new Date(o.settled_at).toLocaleString('es-MX')):'<button class="btn" data-settle="'+o.id+'">Registrar liquidación</button>')+'</p></article>').join('')+'</div>';$('commissionForm').onsubmit=run(async()=>{const f=formObject('commissionForm');await api('site_config',{site_id:s.id,config:{...s.config,commissionPercent:Number(f.commissionPercent)}});await refresh();await redraw()});host.querySelectorAll('[data-settle]').forEach(b=>b.onclick=run(async()=>{await api('settle',{site_id:s.id,id:b.dataset.settle});await redraw()}));return true}
  if(tab==='customers'){const report=await api('site_report',{site_id:s.id}),contacts=new Map();for(const o of rows){const phone=o.customer.phone.replace(/\D/g,'');if(!contacts.has(phone))contacts.set(phone,{...o.customer,phone,count:0});contacts.get(phone).count++}host.innerHTML='<h3>Clientes y bloqueos</h3><p>Bloqueos por teléfono, limitados a este negocio. No se registran ni bloquean IP en esta plantilla.</p><div class="grid">'+[...contacts.values()].map(u=>{const ban=report.bans.find(b=>b.phone===u.phone);return '<article class="card"><h4>'+esc(u.name)+'</h4><p>'+esc(u.phone)+' · '+u.count+' pedidos recientes</p>'+(ban?'<p>Bloqueado: '+esc(ban.reason)+'</p><button class="btn secondary" data-unban="'+esc(u.phone)+'">Quitar bloqueo</button>':'<button class="btn secondary" data-ban="'+esc(u.phone)+'">Bloquear contacto</button>')+'</article>'}).join('')+'</div>';host.querySelectorAll('[data-unban]').forEach(b=>b.onclick=run(async()=>{await api('customer_unban',{site_id:s.id,phone:b.dataset.unban});await redraw()}));host.querySelectorAll('[data-ban]').forEach(b=>b.onclick=()=>{open('Bloquear contacto','<form id="banCustomer">'+input('reason','Motivo')+input('hours','Horas (vacío: indefinido)','','number')+'<button class="btn">Guardar bloqueo</button></form>');$('banCustomer').onsubmit=run(async()=>{const f=formObject('banCustomer');await api('customer_ban',{site_id:s.id,phone:b.dataset.ban,reason:f.reason,hours:f.hours?Number(f.hours):null});await Business.open(s,'customers')})});return true}
  if(tab==='receipts'){host.innerHTML='<h3>Comprobantes de pedidos</h3><p>Tickets de los últimos 200 pedidos; selecciona una orden para descargar.</p><div class="grid">'+rows.map(o=>'<div>'+card(o)+'<button class="btn secondary" data-receipt="'+o.id+'">'+Icon('download')+'Abrir ticket</button></div>').join('')+'</div>';host.querySelectorAll('[data-receipt]').forEach(b=>b.onclick=()=>receipt(s,rows.find(o=>o.id===b.dataset.receipt)));return true}
  return true;
 }
 function receipt(s,o){const v=s.config;open('Comprobante PED-'+o.folio,'<article class="ticket" id="businessTicket"><div class="ticket-head">'+(v.logo?'<img src="'+esc(v.logo)+'" alt="Logo">':'')+'<h3>'+esc(v.name)+'</h3>'+(v.headerImage?'<img src="'+esc(v.headerImage)+'" alt="Imagen del encabezado">':'')+'</div><h2>'+esc(v.ticketTitle||'Comprobante de pedido')+'</h2><p class="reference">PED-'+o.folio+'</p><p>'+esc(new Date(o.created_at).toLocaleString('es-MX'))+'</p><p>'+esc(o.customer.name)+' · '+esc(o.customer.phone)+'</p><p>Pago: '+esc(labels[o.payment_status])+'</p><table><thead><tr><th>Concepto</th><th>Cantidad</th><th>Precio</th><th>Subtotal</th></tr></thead><tbody>'+o.items.map(p=>'<tr><td>'+esc(p.name)+'</td><td>'+p.qty+'</td><td>'+money(p.price)+'</td><td>'+money(p.subtotal)+'</td></tr>').join('')+'<tr><td>Traslado</td><td>1</td><td>'+money(o.shipping)+'</td><td>'+money(o.shipping)+'</td></tr></tbody></table><strong class="total">TOTAL '+money(o.total)+'</strong><p>'+esc(o.delivery.address||'Recoger en negocio')+'</p><p>Referencia: '+esc(o.reference)+'</p><p>'+esc(v.ticketFinal||'Guarda tu ticket para aclaraciones.')+'</p></article><div class="row">'+button('adminPdf','Descargar PDF','download')+button('adminJpeg','Descargar JPEG','download')+button('backReceipts','Volver','eye')+'</div>');$('backReceipts').onclick=run(()=>Business.open(s,'receipts'));$('adminJpeg').onclick=run(()=>exportTicket(o,'jpeg'));$('adminPdf').onclick=run(()=>exportTicket(o,'pdf'))}
 async function exportTicket(o,format){const canvas=await html2canvas($('businessTicket'),{scale:2,backgroundColor:'#fff',useCORS:true,onclone:doc=>doc.getElementById('businessTicket').classList.add('export-ticket')});if(format==='jpeg'){const a=document.createElement('a');a.href=canvas.toDataURL('image/jpeg',.92);a.download='PED-'+o.folio+'.jpeg';a.click();return}const doc=new jspdf.jsPDF({unit:'mm',format:'a4'}),width=190,height=canvas.height*width/canvas.width,ratio=Math.min(1,277/height);doc.addImage(canvas.toDataURL('image/jpeg',.92),'JPEG',10,10,width*ratio,height*ratio);doc.save('PED-'+o.folio+'.pdf')}
 return {render};
})();
