(function(){
 const c=window.PLATFORM_CONFIG;
 window.Platform={tiles(config={},defaults={}){const m=config.mapMode==='own'||(!config.mapMode&&config.tiles)?config:defaults;let tiles=m.tiles||'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png';return tiles.replaceAll('{apiKey}',encodeURIComponent(m.mapKey||''))},applyAppearance(config={},preferenceKey){
 for(const [field,css] of [['primaryColor','--primary'],['accentColor','--accent']])if(/^#[0-9a-f]{6}$/i.test(config[field]||''))document.documentElement.style.setProperty(css,config[field]);
 let preference=null;try{if(preferenceKey)preference=localStorage.getItem(preferenceKey)}catch{}
 const dark=(preference==='light'||preference==='dark'?preference:config.theme)==='dark';document.documentElement.classList.toggle('dark',dark);document.body.classList.toggle('dark',dark);document.documentElement.style.colorScheme=dark?'dark':'light';
 const color=dark?config.backgroundDark:config.backgroundLight;document.documentElement.style.setProperty('--page-bg',/^#[0-9a-f]{6}$/i.test(color||'')?color:dark?'#0b1118':'#f7f7f9');
 const url=dark?config.backgroundImageDark||config.backgroundImage:config.backgroundImage;
 const patterns={solid:'none',mesh:'radial-gradient(at 0% 0%,color-mix(in srgb,var(--primary) 18%,transparent),transparent 55%),radial-gradient(at 100% 30%,color-mix(in srgb,var(--accent) 16%,transparent),transparent 60%)',stripes:'repeating-linear-gradient(135deg,transparent 0 24px,color-mix(in srgb,var(--text) 4%,transparent) 24px 25px)'};
 const photo=config.backgroundStyle==='image'&&/^https:\/\//.test(url||'');document.body.style.backgroundImage=photo?'linear-gradient(color-mix(in srgb,var(--page-bg) 82%,transparent),color-mix(in srgb,var(--page-bg) 82%,transparent)),url('+JSON.stringify(url)+')':patterns[config.backgroundStyle]||patterns.solid;
 const primary=config.primaryColor||'#c62828',n=parseInt(primary.slice(1),16);const linear=v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4};const luminance=.2126*linear(n>>16&255)+.7152*linear(n>>8&255)+.0722*linear(n&255);document.documentElement.style.setProperty('--on-primary',luminance>.179?'#101820':'#ffffff');
 },async call(action,payload={},jwt){const r=await fetch(c.url+'/functions/v1/saas-platform',{method:'POST',headers:{'Content-Type':'application/json',apikey:c.key,Authorization:'Bearer '+(jwt||c.key)},body:JSON.stringify({action,payload})});const d=await r.json();if(!r.ok)throw Error(d.error||'No se completó la solicitud');return d.data},money(cents){return new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(cents/100)},esc(v){return String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]))}};
})();
