'use strict';
// Reutiliza los módulos del negocio; el servidor comprueba propiedad en cada acción.
const c=PLATFORM_CONFIG,client=supabase.createClient(c.url,c.key),labels=paymentLabels;
let data={sites:[]},bizMap=null,adminSession=null,adminEpoch=0,storeDirty=false;
const run=safe;
function formObject(id){return Object.fromEntries(new FormData($(id)))}
function field(name,label,value='',type='text'){return '<label>'+esc(label)+'<input name="'+esc(name)+'" type="'+type+'" value="'+esc(value)+'" '+(type==='number'?'step="0.01" min="0"':'')+'></label>'}
function clearAdminMap(){if(bizMap){bizMap.remove();bizMap=null}}
function open(title,body){clearAdminMap();$('editor').classList.remove('business-editor');$('editorTitle').textContent=title;$('editorBody').innerHTML=body;if(!$('editor').open)$('editor').showModal()}
async function api(action,payload={}){const auth=await client.auth.getSession();if(!auth.data.session)throw Error('Inicia sesión');const result=await call(action,payload,auth.data.session.access_token);if(['site_config','product','order_decision','order_payment_decision'].includes(action))storeDirty=true;return result}
async function refresh(){const epoch=++adminEpoch;const auth=await client.auth.getSession();adminSession=auth.data.session;$('businessAdmin').hidden=true;data={sites:[]};$('account').ariaLabel=adminSession?'Mi cuenta':'Iniciar sesión';if(!adminSession)return;const dashboard=await call('dashboard',{},adminSession.access_token);if(epoch!==adminEpoch)return;data={sites:dashboard.sites.filter(s=>s.slug===slug),map_defaults:dashboard.map_defaults};$('businessAdmin').hidden=!data.sites.length}
async function enterAdmin(){await refresh();if(!adminSession)return account();if(!data.sites.length)return message('Esta cuenta no tiene acceso a la administración de este negocio');await Business.open(data.sites[0])}
function account(){if(adminSession){open('Mi cuenta','<p>'+esc(adminSession.user?.email||'Sesión iniciada')+'</p>'+(data.sites.length?'<button class="btn" id="openBusiness">'+Icon('gear')+'Administrar este negocio</button>':'<p>Tu cuenta no tiene permisos de administración en este negocio.</p>')+'<button class="btn secondary" id="signOut">Cerrar sesión</button>');if($('openBusiness'))$('openBusiness').onclick=run(enterAdmin);$('signOut').onclick=run(async()=>{await client.auth.signOut();await refresh();$('editor').close();$('editorBody').innerHTML='' });return}
open('Iniciar sesión','<form id="storeLogin"><label>Correo electrónico<input name="email" type="email" required autocomplete="username"></label><label>Contraseña<input name="password" type="password" required autocomplete="current-password"></label><button class="btn">Iniciar sesión</button></form><p><button class="btn secondary" id="storeGoogle">'+Icon('user')+'Continuar con Google</button></p><p>Utiliza la cuenta propietaria de este negocio. Iniciar sesión no otorga permisos de administrador.</p>');$('storeLogin').onsubmit=run(async()=>{const result=await client.auth.signInWithPassword(formObject('storeLogin'));if(result.error)throw result.error;await refresh();if(data.sites.length)await Business.open(data.sites[0]);else account()});$('storeGoogle').onclick=run(async()=>{const result=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.href}});if(result.error)throw result.error})}
$('account').innerHTML=Icon('user');$('businessAdmin').innerHTML=Icon('gear');$('closeEditor').innerHTML=Icon('close');$('account').onclick=run(async()=>{await refresh();account()});$('businessAdmin').onclick=run(enterAdmin);$('adminEntry').onclick=run(enterAdmin);$('closeEditor').onclick=()=>$('editor').close();$('editor').addEventListener('close',()=>{clearAdminMap();if(storeDirty)location.reload()});
client.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT'){adminEpoch++;adminSession=null;data={sites:[]};$('businessAdmin').hidden=true;clearAdminMap();$('editorBody').innerHTML='';$('editor').close()}else setTimeout(()=>refresh().catch(e=>message(e.message)),0)});
refresh().catch(e=>message(e.message));
