'use strict';
window.StoreDesign=(()=>{
 let offset=0,timer=null;
 const now=()=>Date.now()+offset;
 function active(p){return p.active!==false&&Number.isFinite(Date.parse(p.startsAt))&&Number.isFinite(Date.parse(p.endsAt))&&Date.parse(p.startsAt)<=now()&&Date.parse(p.endsAt)>now()}
 function price(product,config){return (config.promotions||[]).filter(p=>active(p)&&p.productId===product.id&&Number.isInteger(p.price)&&p.price>=0&&p.price<product.price).reduce((n,p)=>Math.min(n,p.price),product.price)}
 function render(){if(!site)return;const host=$('promotions'),list=(site.config.promotions||[]).filter(active);host.hidden=!list.length;host.innerHTML=list.map(p=>'<article class="promotion promotion-'+(p.style==='spotlight'?'spotlight':p.style==='card'?'card':'banner')+'">'+(image(p.image)?'<img src="'+esc(p.image)+'" alt="'+esc(p.title)+'" loading="lazy">':'')+'<div><span class="pill">Promoción por tiempo limitado</span><h3>'+esc(p.title)+'</h3><p>'+esc(p.text)+'</p>'+(p.price!=null&&p.productId?'<strong class="promotion-price">Precio especial '+money(p.price)+'</strong>':'')+(p.productId&&site.products.some(x=>x.id===p.productId)?'<button class="btn secondary" data-promo-product="'+esc(p.productId)+'">Ver producto</button>':'')+'<small>Hasta '+esc(new Date(p.endsAt).toLocaleString('es-MX'))+'</small></div></article>').join('');host.querySelectorAll('[data-promo-product]').forEach(b=>b.onclick=()=>{enter();renderCatalog.category='Todos';$('search').value='';renderCatalog();document.querySelector('[data-product="'+b.dataset.promoProduct+'"]')?.scrollIntoView({behavior:'smooth',block:'center'})})}
 function enter(){$('preMenu').hidden=true;$('menuContent').hidden=false;sessionStorage.setItem('saas.menu.'+slug,'1');$('menuContent').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'start'})}
 function init(s){offset=s.server_time?Date.parse(s.server_time)-Date.now():0;const v=s.config;const intro=$('preMenu');intro.hidden=v.preMenuEnabled===false||sessionStorage.getItem('saas.menu.'+slug)==='1';$('menuContent').hidden=!intro.hidden;$('introTitle').textContent=v.preMenuTitle||'¿Qué se te antoja hoy?';$('introText').textContent=v.preMenuText||'Explora el menú, elige tus favoritos y prepara tu pedido para recoger o recibir en casa.';if(image(v.preMenuImage)){$('introImage').src=v.preMenuImage;$('introImage').hidden=false}else $('introImage').hidden=true;$('enterMenu').innerHTML=Icon('cart')+'Ver menú';$('enterMenu').onclick=enter;$('backPreMenu').innerHTML=Icon('site')+'Inicio';$('backPreMenu').hidden=v.preMenuEnabled===false;$('backPreMenu').onclick=()=>{intro.hidden=false;$('menuContent').hidden=true;sessionStorage.removeItem('saas.menu.'+slug);intro.scrollIntoView({behavior:'smooth'})};render();clearTimeout(timer);schedule()}
 function schedule(){const boundaries=(site.config.promotions||[]).flatMap(p=>[Date.parse(p.startsAt),Date.parse(p.endsAt)]).filter(t=>t>now());if(!boundaries.length)return;timer=setTimeout(()=>{render();renderCatalog();if($('orderForm')){capture();cart()}schedule()},Math.min(2147483000,Math.max(50,Math.min(...boundaries)-now()+20)))}
 document.addEventListener('visibilitychange',()=>{if(!document.hidden&&site){render();renderCatalog();if($('orderForm')){capture();cart()}clearTimeout(timer);schedule()}});
 return {init,render,price,active,enter};
})();
